<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionRepository extends EntityRepository
{
    public function findByQuestion() {
        $qb = $this->createQueryBuilder('q')
                ->select('q')
                ->join('q.question', 'qq')
                ->where('qq.del = :del')
                ->setParameter('del', 0);
        return $qb->getQuery()
                        ->getResult();
    }

}
