<?php
namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
    public function findWithAnswers($id)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT q, a FROM BKVotingBundle:Question q JOIN q.answers a WHERE q.id = :id'
        )->setParameter('id', $id);

        return $query->getResult();
    }
}
