<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository {

    public function findByUser($user) {
        $qb = $this->createQueryBuilder('v')
                ->select('v')
                ->join('v.answers', 'a')
                ->join('a.answer', 'aa')
                ->join('aa.question', 'q')
                ->where('q.del = :del')
                ->andWhere('v.user = :user')
                ->setParameter('user', $user)
                ->setParameter('del', 0);
        return $qb->getQuery()
                        ->getResult();
    }

    public function findByNote($user) {
        $qb = $this->createQueryBuilder('v')
                ->select('v')
                ->where('v.note IS NOT NULL')
                ->andWhere('v.user = :user')
                ->setParameter('user', $user);
        return $qb->getQuery()
                        ->getResult();
    }

    public function CountOfVote($user) {
        return $this->createQueryBuilder('t')
                        ->select('count(t.id)')
                        ->where('t.user = :user')
                        ->setParameter('user', $user->getId())
                        ->getQuery()
                        ->getSingleScalarResult();
    }

    public function CountOfNoteVote($user) {
        return $this->createQueryBuilder('t')
                        ->select('count(t.id)')
                        ->where('t.note IS NOT NULL')
                        ->andWhere('t.user = :user')
                        ->setParameter('user', $user->getId())
                        ->getQuery()
                        ->getSingleScalarResult();
    }

}
